- alias: 'Turn off outside lights at sunrise'
  trigger:
    platform: sun
    event: 'sunrise'
    offset: '00:30:00'
  action:
    service: light.turn_off
    entity_id: light.porch_light

- alias: 'Turn on outside lights at sunset'
  trigger:
    platform: sun
    event: 'sunset'
    offset: '-00:30:00'
  action:
    service: light.turn_on
    entity_id: light.porch_light

- alias: 'Send notification Front Door or Garage Opens'
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.0c51011b025e
    state: not_home 
  action:
    service: notify.pbnotify
    data:
      message: "Front or Garage Door Opened"
      title: "Security Alert!"

- alias: 'Send notification when Patio Door Opens'
  trigger:
    platform: state
    entity_id: binary_sensor.back_door
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.0c51011b025e
    state: not_home
  action:
    service: notify.pbnotify
    data:
      message: "Patio Door Opened"
      title: "Security Alert!"

- alias: 'Turn on downlight when there is movement'
  trigger:
    platform: state
    entity_id: binary_sensor.living_room
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:     
      - condition: time
        after: '21:00'
        before: '07:15'
      - condition: state
        entity_id: 'light.downlight'
        state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: script.downlight_movement_on_5m

- alias: 'Turn on foyer when entering house'
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'off'
    to: 'on'
  condition:
    condition: sun
    after: sunset
    after_offset: "-1:00:00"
  action:
    service: homeassistant.turn_on
    entity_id: script.foyer_turn_on_3m

- alias: 'Turn on Zachs room light'
  trigger:
    platform: time
    after: '06:15'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
         - mon
         - tue
         - wed
         - thu
         - fri
      - condition: state
        entity_id: input_boolean.wake_zach
        state: 'on' 
  action:
    service: homeassistant.turn_on
    entity_id: script.zach_light_on_2h

- alias: 'Turn off lights when leaving'
  trigger:
    platform: time
    after: '07:15'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
         - mon
         - tue
         - wed
         - thu
         - fri
      - condition: state
        entity_id: input_boolean.wake_zach
        state: 'on'
  action:
    - service: homeassistant.turn_off
      entity_id: group.all_lights
    - service: homeassistant.turn_off
      entity_id: group.all_switches


- alias: 'Turn on lights for work and school week'
  trigger:
    platform: time
    after: '06:15'
  condition:
    condition: and
    conditions:
      - condition: time
        weekday:
         - mon
         - tue
         - wed
         - thu
         - fri
      - condition: state
        entity_id: input_boolean.wake_zach
        state: 'on'
  action:
    - service: light.turn_on
      entity_id: light.downlight
    - service: light.turn_on
      entity_id: light.living_room_table
