- alias: 'Turn off outside lights at sunrise'
  trigger:
    platform: sun
    event: 'sunrise'
    offset: '00:30:00'
  action:
    service: light.turn_off
    entity_id: light.porch_light

- alias: 'Turn on outside lights at sunset'
  trigger:
    platform: sun
    event: 'sunset'
    offset: '-00:30:00'
  action:
    service: light.turn_on
    entity_id: light.porch_light

- alias: 'Send notification Front Door or Garage Opens'
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.60f189e3ca47
    state: not_home 
  action:
    service: notify.pbnotify
    data:
      message: "Front or Garage Door Opened"
      title: "Security Alert!"

- alias: 'Send notification when Patio Door Opens'
  trigger:
    platform: state
    entity_id: binary_sensor.back_door
    from: 'off'
    to: 'on'
  condition:
    condition: state
    entity_id: device_tracker.60f189e3ca47
    state: not_home
  action:
    service: notify.pbnotify
    data:
      message: "Patio Door Opened"
      title: "Security Alert!"

- alias: 'Turn on downlight when there is movement'
  trigger:
    platform: state
    entity_id: binary_sensor.living_room
    from: 'off'
    to: 'on'
  condition:
    condition: and
    conditions:     
      - condition: time
        after: '22:00'
        before: '07:00'
      - condition: state
        entity_id: 'light.downlight'
        state: 'off'
  action:
    service: homeassistant.turn_on
    entity_id: script.downlight_movement_on_5m

- alias: 'Turn on foyer when entering house'
  trigger:
    platform: state
    entity_id: binary_sensor.front_door
    from: 'off'
    to: 'on'
  condition:
    condition: sun
    after: sunset
  action:
    service: homeassistant.turn_on
    entity_id: script.foyer_turn_on_3m

- alias: 'Turn on Zachs room light'
  trigger:
    platform: time
    after: '06:30'
  condition:
    condition: time
    weekday:
     - mon
     - tue
     - wed
     - thu
     - fri
  action:
    service: homeassistant.turn_on
    entity_id: script.zach_light_on_2h

