homeassistant:
  name: Home
  latitude: !secret lati
  longitude: !secret longi
  elevation: 216
#  temperature_unit: F
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

group: !include group.yaml
http:
  api_password: !secret http_password
  ssl_certificate: /home/pi/.homeassistant/fullchain.pem
  ssl_key: /home/pi/.homeassistant/privkey.pem

recorder:
  purge_days: 90

logger:
  default: critical

sun:

frontend:

discovery:

# Checks for available updates
#updater:

# Allows you to issue voice commands from the frontend
#conversation:

history:

sensor:
  platform: time_date
  display_options:
    - 'date_time'

# Prediction of weather
sensor 2:
  platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - summary
    - icon
    - nearest_storm_distance
    - precip_probability
    - temperature
    - apparent_temperature
    - wind_speed
    - humidity
    - pressure
    - hourly_summary
    - daily_summary


sensor 3:
  platform: speedtest
  minute: 
    - 0
    - 30
  monitored_conditions:
    - ping

sensor 4:
  platform: steam_online
  api_key: 5A07C022C819060052840752BA4142DF
  accounts: 
    - 76561197966512456
    - 76561198158256106
    - 76561197980617560    

zone:
  name: Home
  latitude: !secret lati
  longitude: !secret longi
  icon: mdi:castle  

zone 2:
  name: Work
  latitude: 30.486485
  longitude: -97.6619547
  icon: mdi:worker

wink:
#  access_token: !secret wink_token
#  refresh_token: !secret wink_refresh
  email: !secret wink_email
  password: !secret wink_password
  client_id: !secret wink_client_id
  client_secret: !secret wink_client_secret



ifttt:
  key: !secret ifttt_token

nest:
  username: !secret nest_user
  password: !secret nest_pass



climate:
  platform: nest


media_player:
  - platform: cast
    host: 10.0.200.10
    name: Chromecast  

device_tracker:
  platform: asuswrt
  host: 10.3.200.28
  protocol: telnet
  mode: ap
  username: !secret asus_user
  password: !secret asus_pass

  # If new discovered devices are tracked by default (default: yes)
  track_new_devices: no
  # Seconds between each scan for new devices (default: 12)
  interval_seconds: 600
  # Seconds to wait till marking someone as not home after not being seen
  # (default: 180)
  consider_home: 180

notify:
  platform: pushbullet
  api_key: !secret push_bullet_api
  name: pbnotify

envisalink:
#optional
  port: 4025
  evl_version: 4
  keepalive_interval: 60
  zonedump_interval: 30

#required
  host: 10.3.100.100
  panel_type: HONEYWELL
  user_name: !secret alarm_user
  password: !secret alarm_pass
  code: !secret alarm_code

  zones:
    1: 
      name: 'Front Door'
      type: 'opening'

    2:
      name: 'Living Room'
      type: 'motion'

    3:
      name: 'Front Windows'
      type: 'opening'

    4: 
      name: 'Rooms'
      type: 'opening'

    5:
      name: 'Back Door'
      type: 'opening'

    6:
      name: 'Master'
      type: 'opening'

  partitions:
    1:
      name: 'Home Alarm'

switch:
  - platform: wake_on_lan
    host: 10.3.3.100
    mac_address: d4-3d-7e-e2-6b-2b

shell_command:
  xbox_poweron: xbox-on --ip=10.3.200.25 --live_device_id=FD004A360F3C5158 


alexa: !include alexa.yaml

scene: !include scene.yaml
automation: !include automation.yaml
script: !include script.yaml 
